POST http://localhost:3000/alarms
Content-Type: application/json

{
  "name": "test",
  "time": "12:30",
  "abbreviation": "AM",
  "repeatDays": ["Sunday", "Monday"],
  "soundDuration": "5",
  "snooze" : "true"
}
###
GET http://localhost:3000/alarms

### 
DELETE http://localhost:3000/alarms/649bac706678357b013358e4

###
PATCH http://localhost:3000/alarms/649bacb2275caf7b4f106be3
Content-Type: application/json

{
  "name": "test2",
  "time": "12:30",
  "abbreviation": "PM",
  "repeatDays": ["Sunday", "Monday"],
  "soundDuration": "5",
  "snooze" : "true"
}