POST http://localhost:3000/alarms
Content-Type: application/json

{
  "name": "test",
  "time": "12:30",
  "abbreviation": "PM",
  "repeatDays": ["Sunday", "Monday"]
}
###
GET http://localhost:3000/alarms

### 
DELETE http://localhost:3000/alarms/6493790fe205c3c2aa81b265